apiVersion: "v1"
kind: "Service"
metadata:
  name: "postgres-elections"
  labels:
    app: "postgres-elections"
spec:
  ports:
  - port: 5432
    name: "postgres-elections"
  clusterIP: "None"
  selector:
    app: "postgres-elections"
---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "postgres-elections"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "postgres-elections"
  template:
    metadata:
      labels:
        app: "postgres-elections"
    spec:
      containers:
      - name: "postgres-elections"
        image: "postgres:latest"
        env:
        - name: "POSTGRES_DB"
          valueFrom:
            secretKeyRef:
              name: "creds-elections"
              key: "PGDATABASE"
        - name: "POSTGRES_USER"
          valueFrom:
            secretKeyRef:
              name: "creds-elections"
              key: "PGUSER"
        - name: "POSTGRES_PASSWORD"
          valueFrom:
            secretKeyRef:
              name: "creds-elections"
              key: "PGPASSWORD"
        ports:
        - containerPort: 5432
          name: postgredb-elections
---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "electionsbot"
  namespace: "default"
  labels:
    app: "electionsbot"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "electionsbot"
  template:
    metadata:
      labels:
        app: "electionsbot"
    spec:
      containers:
      - name: "electionsbot"
        image: "cyberdiscovery/electionsbot:latest"
        env:
        - name: "BOT_TOKEN"
          valueFrom:
            secretKeyRef:
              name: "creds"
              key: "BOT_TOKEN"
        - name: "PGHOST"
          value: "postgres-elections"
        - name: "PGPORT"
          valueFrom:
            secretKeyRef:
              name: "creds-elections"
              key: "PGPORT"
        - name: "PGDATABASE"
          valueFrom:
            secretKeyRef:
              name: "creds-elections"
              key: "PGDATABASE"
        - name: "PGUSER"
          valueFrom:
            secretKeyRef:
              name: "creds-elections"
              key: "PGUSER"
        - name: "PGPASSWORD"
          valueFrom:
            secretKeyRef:
              name: "creds-elections"
              key: "PGPASSWORD"
